### ISSUE TITLE
Test installation script on travis

### ISSUE THREAD

**Issue by mkhl** [exercism/cli-www#8]
Broken installers suck. We could consider testing this one on travis to make sure it doesn't.
That could also help us discover unusual `uname` outputs to handle.

#5 would help here.

**Comment by roseaboveit** [comment]
@kytrinyx Just to confirm, this hasn't yet been done correct? Is this the sort of thing we can just add a tag to, to allow folks to work on? Or does it require more discussion?

**Comment by kytrinyx** [comment]
After thinking this through a bit, I don't know if we could test this well on Travis, since the installer should work on a number of different machines (linux 32-bit, linux 64 bit, mac 32 bit, mac 64 bit). We would only be able to test one execution path.

I've been slowly moving away from the idea of the installation script.

This script hasn't changed in a very long time, and I don't expect it to change much in the future. I think that in retrospect it's not worth adding a test. I'm going to close this.
